# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jason Eiben
tagline:          'Full stack developer, teacher, tinkerer'
description:      'Full stack developer, teacher, tinkerer'
url:              http://mreiben.github.io
baseurl:          /

author:
  name:           'Jason Eiben'
  url:            https://twitter.com/Mr_Eiben

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
