# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jason Eiben
tagline:          'Full stack developer, teacher, tinkerer'
description:      'Full stack developer, teacher, tinkerer'
url:              https://mreiben.github.io
baseurl:          https://mreiben.github.io/

author:
  name:           'Jason Eiben'
  url:            https://twitter.com/Mr_Eiben

paginate:         5

github:
  repo:           https://github.com/mreiben
